#!/usr/bin/env python3
# deploy-swa.py
#
# Build the SPA frontend with cloud-specific environment variables from src/.env,
# then deploy to Azure Static Web Apps.
#
# What this script does:
#   1. Read src/.env (synced by sync-infra-env.py) to obtain cloud-specific values
#   2. Write a temporary .env.production file with the cloud API URLs
#   3. Run `npm run build` in src/frontend (Vite embeds the env vars at build time)
#   4. Deploy the built `dist/` directory to SWA using the deployment token
#
# The SWA deployment token is sensitive and not stored in .env.
# It is read from `terraform output -raw swa_deployment_token`.
#
# Prerequisites:
#   - src/.env populated (run `python src/scripts/sync-infra-env.py` first)
#   - terraform CLI on PATH with state in src/infra (for deployment token only)
#   - node / npm on PATH
#   - npm dependencies installed in src/frontend (`npm install`)
#   - python-dotenv installed (`pip install python-dotenv`)
#
# Usage:
#   python src/frontend/scripts/deploy-swa.py
#   python src/frontend/scripts/deploy-swa.py --skip-build   # deploy only (reuse existing dist/)

import argparse
import subprocess
import sys
from pathlib import Path

from dotenv import dotenv_values

SCRIPT_DIR = Path(__file__).resolve().parent
FRONTEND_DIR = SCRIPT_DIR.parent
SRC_DIR = FRONTEND_DIR.parent
INFRA_DIR = SRC_DIR / "infra"
DIST_DIR = FRONTEND_DIR / "dist"
DOTENV_PATH = SRC_DIR / ".env"

# Vite reads envDir='../' (= src/) so we write the production env file there.
ENV_PRODUCTION = SRC_DIR / ".env.production"

# .env variable names that Vite needs at build time.
# Must match vite.config.ts envPrefix: ENTRA_, RESOURCE_API_, FOUNDRY_, BACKEND_
VITE_ENV_KEYS: list[str] = [
    "ENTRA_TENANT_ID",
    "ENTRA_SPA_APP_CLIENT_ID",
    "ENTRA_RESOURCE_API_CLIENT_ID",
    "ENTRA_RESOURCE_API_SCOPE",
    "RESOURCE_API_URL",
    "BACKEND_API_URL",
]


def load_dotenv_values() -> dict[str, str]:
    """Load src/.env and return as dict."""
    if not DOTENV_PATH.exists():
        print(f"ERROR: {DOTENV_PATH} not found. Run sync-infra-env.py first.", file=sys.stderr)
        sys.exit(1)
    return {k: v for k, v in dotenv_values(DOTENV_PATH).items() if v}


def get_deployment_token() -> str:
    """Read the SWA deployment token from terraform (sensitive output)."""
    result = subprocess.run(
        ["terraform", "output", "-raw", "swa_deployment_token"],
        capture_output=True,
        text=True,
        cwd=INFRA_DIR,
    )
    if result.returncode != 0 or not result.stdout.strip():
        print("ERROR: could not read swa_deployment_token from terraform output", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def write_env_production(env: dict[str, str]) -> None:
    """Write .env.production with cloud-specific values for Vite build.

    Vite resolves env files by mode. When running `npm run build` (mode=production),
    .env.production takes precedence over .env. This function writes a temporary
    .env.production so that the production build embeds cloud API URLs instead of
    local dev values. The file is deleted after deployment (see main()).
    """
    lines = ["# Auto-generated by deploy-swa.py — do not edit manually"]
    for key in VITE_ENV_KEYS:
        value = env.get(key, "")
        if not value:
            print(f"WARNING: {key} is empty in .env", file=sys.stderr)
        lines.append(f"{key}={value}")

    ENV_PRODUCTION.write_text("\n".join(lines) + "\n")
    print(f"Wrote {ENV_PRODUCTION}")


def build_frontend() -> None:
    """Run npm run build in the frontend directory."""
    print("\n--- Building frontend ---")
    result = subprocess.run(
        ["npm", "run", "build"],
        cwd=FRONTEND_DIR,
    )
    if result.returncode != 0:
        print("ERROR: frontend build failed", file=sys.stderr)
        sys.exit(result.returncode)
    print(f"Build output: {DIST_DIR}")


def deploy_swa(deployment_token: str) -> None:
    """Deploy dist/ to Azure Static Web Apps using swa CLI."""
    print("\n--- Deploying to Static Web App ---")
    result = subprocess.run(
        [
            "npx",
            "@azure/static-web-apps-cli",
            "deploy",
            str(DIST_DIR),
            "--deployment-token",
            deployment_token,
            "--env",
            "production",
        ],
        cwd=FRONTEND_DIR,
    )
    if result.returncode != 0:
        print("ERROR: swa deploy failed", file=sys.stderr)
        sys.exit(result.returncode)
    print("Deploy succeeded!")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build and deploy SPA to Azure Static Web Apps")
    parser.add_argument(
        "--skip-build", action="store_true", help="Skip npm build, deploy existing dist/"
    )
    args = parser.parse_args()

    # 1. Load .env values
    print("--- Reading src/.env ---")
    env = load_dotenv_values()

    # 2. Get deployment token (sensitive — from terraform only)
    print("--- Reading deployment token from terraform ---")
    deployment_token = get_deployment_token()

    # 3. Write .env.production for Vite build
    write_env_production(env)

    # 4. Build
    if not args.skip_build:
        build_frontend()
    else:
        if not DIST_DIR.is_dir():
            print(f"ERROR: --skip-build specified but {DIST_DIR} does not exist", file=sys.stderr)
            sys.exit(1)
        print("Skipping build (--skip-build)")

    # 5. Deploy
    deploy_swa(deployment_token)

    # 6. Cleanup
    if ENV_PRODUCTION.exists():
        ENV_PRODUCTION.unlink()
        print(f"Cleaned up {ENV_PRODUCTION}")

    swa_url = env.get("FRONTEND_SPA_APP_URL", "")
    if swa_url:
        print(f"\nSPA is live at: {swa_url}")


if __name__ == "__main__":
    main()
